
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 21:22:44 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 50;
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int LPAREN = 13;
  public static final int SEMI = 7;
  public static final int CONTINUE = 20;
  public static final int NUM_CONST = 48;
  public static final int MINUS = 29;
  public static final int RPAREN = 14;
  public static final int AND = 28;
  public static final int LTHAN = 36;
  public static final int OR = 27;
  public static final int COMMA = 8;
  public static final int CLASS = 11;
  public static final int INC = 25;
  public static final int DIV = 40;
  public static final int PLUS = 38;
  public static final int ASSIGN = 6;
  public static final int IF = 16;
  public static final int THIS = 46;
  public static final int LETHAN = 37;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 32;
  public static final int SUPER = 43;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int MOD = 41;
  public static final int IDENT = 47;
  public static final int BREAK = 19;
  public static final int VOID = 15;
  public static final int GTHAN = 34;
  public static final int COLON = 42;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int READ = 45;
  public static final int ENUM = 44;
  public static final int GOTO = 23;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int GETHAN = 35;
  public static final int BOOL_CONST = 49;
  public static final int DEC = 26;
  public static final int PRINT = 22;
  public static final int DO = 17;
  public static final int UNEQUAL = 33;
}

